export const COUNTRIES = [
  { name: "United Arab Emirates", code: "AE", dial: "+971" },
  { name: "Saudi Arabia", code: "SA", dial: "+966" },
  { name: "Qatar", code: "QA", dial: "+974" },
  { name: "Kuwait", code: "KW", dial: "+965" },
  { name: "Bahrain", code: "BH", dial: "+973" },
  { name: "Oman", code: "OM", dial: "+968" },
  { name: "Egypt", code: "EG", dial: "+20" },
  { name: "Jordan", code: "JO", dial: "+962" },
  { name: "Lebanon", code: "LB", dial: "+961" },
  { name: "Iraq", code: "IQ", dial: "+964" },
  { name: "Syria", code: "SY", dial: "+963" },
  { name: "Yemen", code: "YE", dial: "+967" },
  { name: "Palestine", code: "PS", dial: "+970" },
  { name: "Sudan", code: "SD", dial: "+249" },
  { name: "Libya", code: "LY", dial: "+218" },
  { name: "Tunisia", code: "TN", dial: "+216" },
  { name: "Algeria", code: "DZ", dial: "+213" },
  { name: "Morocco", code: "MA", dial: "+212" },
  { name: "Mauritania", code: "MR", dial: "+222" },
  { name: "Somalia", code: "SO", dial: "+252" },
  { name: "Djibouti", code: "DJ", dial: "+253" },
  { name: "Comoros", code: "KM", dial: "+269" },
  { name: "Turkey", code: "TR", dial: "+90" },
  { name: "Iran", code: "IR", dial: "+98" },
  { name: "Pakistan", code: "PK", dial: "+92" },
  { name: "India", code: "IN", dial: "+91" },
  { name: "Bangladesh", code: "BD", dial: "+880" },
  { name: "Sri Lanka", code: "LK", dial: "+94" },
  { name: "Nepal", code: "NP", dial: "+977" },
  { name: "Afghanistan", code: "AF", dial: "+93" },
  { name: "China", code: "CN", dial: "+86" },
  { name: "Hong Kong", code: "HK", dial: "+852" },
  { name: "Singapore", code: "SG", dial: "+65" },
  { name: "Malaysia", code: "MY", dial: "+60" },
  { name: "Indonesia", code: "ID", dial: "+62" },
  { name: "Philippines", code: "PH", dial: "+63" },
  { name: "Thailand", code: "TH", dial: "+66" },
  { name: "Vietnam", code: "VN", dial: "+84" },
  { name: "South Korea", code: "KR", dial: "+82" },
  { name: "Japan", code: "JP", dial: "+81" },
  { name: "United Kingdom", code: "GB", dial: "+44" },
  { name: "United States", code: "US", dial: "+1" },
  { name: "Canada", code: "CA", dial: "+1" },
  { name: "Australia", code: "AU", dial: "+61" },
  { name: "New Zealand", code: "NZ", dial: "+64" },
  { name: "Ireland", code: "IE", dial: "+353" },
  { name: "France", code: "FR", dial: "+33" },
  { name: "Germany", code: "DE", dial: "+49" },
  { name: "Italy", code: "IT", dial: "+39" },
  { name: "Spain", code: "ES", dial: "+34" },
  { name: "Portugal", code: "PT", dial: "+351" },
  { name: "Netherlands", code: "NL", dial: "+31" },
  { name: "Belgium", code: "BE", dial: "+32" },
  { name: "Switzerland", code: "CH", dial: "+41" },
  { name: "Austria", code: "AT", dial: "+43" },
  { name: "Sweden", code: "SE", dial: "+46" },
  { name: "Norway", code: "NO", dial: "+47" },
  { name: "Denmark", code: "DK", dial: "+45" },
  { name: "Finland", code: "FI", dial: "+358" },
  { name: "Poland", code: "PL", dial: "+48" },
  { name: "Romania", code: "RO", dial: "+40" },
  { name: "Greece", code: "GR", dial: "+30" },
  { name: "Cyprus", code: "CY", dial: "+357" },
  { name: "Russia", code: "RU", dial: "+7" },
  { name: "Ukraine", code: "UA", dial: "+380" },
  { name: "Belarus", code: "BY", dial: "+375" },
  { name: "South Africa", code: "ZA", dial: "+27" },
  { name: "Nigeria", code: "NG", dial: "+234" },
  { name: "Kenya", code: "KE", dial: "+254" },
  { name: "Ethiopia", code: "ET", dial: "+251" },
  { name: "Ghana", code: "GH", dial: "+233" },
  { name: "Tanzania", code: "TZ", dial: "+255" },
  { name: "Uganda", code: "UG", dial: "+256" },
  { name: "Brazil", code: "BR", dial: "+55" },
  { name: "Argentina", code: "AR", dial: "+54" },
  { name: "Mexico", code: "MX", dial: "+52" },
  { name: "Chile", code: "CL", dial: "+56" },
  { name: "Colombia", code: "CO", dial: "+57" },
  { name: "Peru", code: "PE", dial: "+51" },
  { name: "Venezuela", code: "VE", dial: "+58" },
  { name: "Other", code: "XX", dial: "+" },
];